Repository wirepas/backend-client, pull requests merged in 2020-01, with the labels that each got.

#195 Diagnostics cbor ids
  tests/files/received_messages.json
  wirepas_backend_client/messages/decoders/diagnostics.json
Labels: framework/apdus

#196 Update version to v1.2.2.rc3
  wirepas_backend_client/__about__.py
Labels: packaging

#197 Mesh request example
  examples/publish_request.py
Labels: framework/examples

#203 cli: fix data tracking exception
  wirepas_backend_client/cli.py
Labels: framework/bug, framework/entrypoints

#202 Update travis
  .ci/create_release.sh
  .ci/install-requirements.sh
  .ci/releases.sh
  .ci/service-tests.sh
  .ci/services/docker-compose.yml
  .ci/services/mysql/Dockerfile
  .ci/services/mysql/db_create.sql
  .ci/services/test-secrets
  .ci/unit-tests.sh
  .travis.yml
  CHANGELOG.md
  tests/services/docker-compose.yml
  tests/services/test-secrets
Labels: integration/travis

#201 Diagnostics dashboard
  examples/dashboards/diagnostics.ndjson
Labels: framework/examples

#206 Release helper
  .ci/create_release.sh
Labels: packaging

#200 Advertiser message: interface compliance
  examples/dashboards/kpi_adv_dashboard.ndjson
  wirepas_backend_client/api/mysql/connectors.py
  wirepas_backend_client/messages/decoders/advertiser.py
  wirepas_backend_client/messages/decoders/generic.py
  wirepas_backend_client/test/kpi_adv.py
Labels: framework/interfaces, framework/kpi

#212 Update ruuvi.py
  wirepas_backend_client/messages/decoders/ruuvi.py
Labels: framework/apdus, framework/bug

#209 Diagnostic decoder
  tests/decode_apdu.py
  tests/files/apdu_decode.json
  wirepas_backend_client/messages/decoders/diagnostics.py
  wirepas_backend_client/tools/utils.py
Labels: framework/apdus, framework/bug

#215 Release v1.2.3
  CHANGELOG.md
  wirepas_backend_client/__about__.py
Labels: packaging

#218 Endpoint property
  wirepas_backend_client/messages/decoders/diagnostics.py
  wirepas_backend_client/messages/decoders/generic.py
Labels: framework/apdus, framework/bug

#221 Dockerfile simplification
  .dockerignore
  README.md
  container/alpine/Dockerfile
  container/docker-compose.yml
  container/slim/Dockerfile
Labels: integration/docker

#181 Change .settings to settings/examples.yml
  .dockerignore
  .gitignore
  README.md
  container/docker-compose.yml
  setup.py
  tests/services/docker-compose.yml
Labels: documentation, integration/docker

#222 ADV decoder
  wirepas_backend_client/messages/decoders/advertiser.py
Labels: framework/kpi

#220 Update adv mysql schema
  wirepas_backend_client/api/mysql/connectors.py
  wirepas_backend_client/messages/decoders/advertiser.py
Labels: integration/mysql

#225 Advertiser table
  wirepas_backend_client/api/mysql/connectors.py
Labels: framework/kpi

#227 Mysql: received packets
  wirepas_backend_client/api/mysql/connectors.py
  wirepas_backend_client/api/mysql/handlers.py
Labels: integration/mysql

#226 Endpoint map: Class property
  wirepas_backend_client/messages/decoders/generic.py
  wirepas_backend_client/messages/interface.py
Labels: framework/apdus

#224 Disable http cache control
  examples/dashboards/kpi_adv.ndjson
  examples/dashboards/kpi_mesh.ndjson
  tests/test_http_requests.sh
  wirepas_backend_client/api/http.py
  wirepas_backend_client/test/kpi_mesh.py
Labels: framework/interfaces

#233 Update container workdir
  container/alpine/Dockerfile
  container/slim/Dockerfile
Labels: integration/docker

#231 Test network application
  wirepas_backend_client/api/mysql/connectors.py
  wirepas_backend_client/messages/decoders/testnw.py
Labels: framework/bug, integration/mysql

#234 Release v1.2.4
  CHANGELOG.md
  wirepas_backend_client/__about__.py
Labels: packaging

#235 Wirepas provisioning server example.
  .ci/service-tests.sh
  .ci/unit-tests.sh
  README.md
  examples/provisioning_config.yml
  examples/settings.yml
  requirements.txt
  setup.py
  tests/services/docker-compose.yml
  wirepas_backend_client/__main__.py
  wirepas_backend_client/provisioning/__init__.py
  wirepas_backend_client/provisioning/data.py
  wirepas_backend_client/provisioning/events.py
  wirepas_backend_client/provisioning/message.py
  wirepas_backend_client/provisioning/provisioning_server.py
  wirepas_backend_client/provisioning/sm.py
Labels: framework/entrypoints

#237 MQTT subscriber filters for MQTT viewer
  examples/mqtt_viewer.py
Labels: framework/examples

#238 Flatten serialization
  tests/decode_apdu.py
  tests/files/apdu_decode.json
  wirepas_backend_client/tools/utils.py
Labels: framework/apdus, framework/examples

#240 Release v1.3.0
  CHANGELOG.md
  wirepas_backend_client/__about__.py
Labels: packaging

#236 Update gw cli
  wirepas_backend_client/__main__.py
  wirepas_backend_client/cli.py
  wirepas_backend_client/cli/__init__.py
  wirepas_backend_client/cli/__main__.py
  wirepas_backend_client/cli/gateway.py
  wirepas_backend_client/cli/shell.py
  wirepas_backend_client/mesh/network.py
  wirepas_backend_client/mesh/state.py
Labels: framework/entrypoints
