Repository wirepas/backend-client, pull requests merged in 2020-02, with the labels that each got.

#246 Diagnostic cbor ids
  wirepas_backend_client/messages/decoders/diagnostics.json
Labels: framework/apdus

#243 Release v1.3.1
  CHANGELOG.md
  wirepas_backend_client/__about__.py
Labels: framework/entrypoints

#251 Change HTTP implementation so that when request destination
  wirepas_backend_client/api/http.py
  wirepas_backend_client/test/kpi_mesh.py
Labels: framework/bug

#254 Black linter fixes round 1
  wirepas_backend_client/api/http.py
Labels: framework/cleanup

#256 Fix list appending issue
  wirepas_backend_client/api/http.py
Labels: framework/bug

#257 Fix comma issue
  wirepas_backend_client/api/http.py
Labels: framework/bug

#259 Merge #250
  wirepas_backend_client/cli/gateway.py
Labels: framework/bug

#260 Fixed broken link
  README.md
Labels: documentation

#263 Fix wait message function
  wirepas_backend_client/cli/gateway.py
  wirepas_backend_client/cli/shell.py
  wirepas_backend_client/mesh/interfaces/mqtt.py
Labels: framework/bug

#265 Change http command request qos=2 and change mqtt default qos =2
  wirepas_backend_client/api/http.py
  wirepas_backend_client/api/mqtt/handlers.py
  wirepas_backend_client/mesh/interfaces/mqtt.py
Labels: framework/http
